Repository ESTSOFT-iOS-01/PomoTodo, pull requests merged in 2025-02, with the labels that each got.

#2 [Chore] PR Templete 및 Github Actions 수정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/main.yml
Labels: ⚙️ chore

#7 [chore] 디자인 시스템 세팅
  PomoTodo/PomoTodo.xcodeproj/project.pbxproj
  PomoTodo/PomoTodo/Info.plist
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/BlueDark.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/BlueDarker.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/BlueNormal.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/ChartBackground.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/CyanDark.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/CyanDarker.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/CyanNormal.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/IndigoDark.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/IndigoDarker.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/IndigoLightHover.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/IndigoNormal.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/TealDark.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/TealDarker.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/TealNormal.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Colors/TimerGray.colorset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/Contents.json
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-Black.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-Bold.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-ExtraBold.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-ExtraLight.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-Light.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-Medium.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-Regular.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-SemiBold.otf
  PomoTodo/PomoTodo/Resources/Fonts/Pretendard-Thin.otf
  PomoTodo/PomoTodo/Sources/App/PomoTodoApp.swift
  PomoTodo/PomoTodo/Sources/Extensions/Font+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/ContentView.swift
Labels: ⚙️ chore

#13 [feature] PomoDay, AppConfig Entity 추가
  PomoTodo/PomoTodo/Sources/Model/Entity/AppConfig.swift
  PomoTodo/PomoTodo/Sources/Model/Entity/PomoDay.swift
Labels: ✨ feature

#18 [feature] Todo 완료 속성 추가
  PomoTodo/PomoTodo/Sources/Model/Entity/PomoDay.swift
Labels: ✨ feature

#15 [feature] 탭바 뷰 개발
  PomoTodo/PomoTodo/Sources/App/PomoTodoApp.swift
  PomoTodo/PomoTodo/Sources/Models/TabModel.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
Labels: ✨ feature

#23 [feature] ToDo 개발
  PomoTodo/PomoTodo/Sources/Extensions/Date+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/UIApplication+Extensions.swift
  PomoTodo/PomoTodo/Sources/Model/Entity/PomoDay.swift
  PomoTodo/PomoTodo/Sources/Views/ContentView.swift
  PomoTodo/PomoTodo/Sources/Views/ToDoView.swift
Labels: ✨ feature

#20 [feature] 타이머 기본 뷰 디자인
  PomoTodo/PomoTodo/Sources/Extensions/UIScreen+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PageControl.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoTimerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoTopView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoView.swift
Labels: ✨ feature

#19 [feature] 통계 View 개발
  PomoTodo/PomoTodo/Sources/Extensions/TimeInterval+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/StaticsView/BarChartBarView.swift
  PomoTodo/PomoTodo/Sources/Views/StaticsView/BarChartView.swift
  PomoTodo/PomoTodo/Sources/Views/StaticsView/SectionView.swift
  PomoTodo/PomoTodo/Sources/Views/StaticsView/StatisticsView.swift
  PomoTodo/PomoTodo/Sources/Views/StatisticsViewModel.swift
Labels: ✨ feature

#26 [Feature] 타이머 활성화 뷰 및 기능 개발
  PomoTodo/PomoTodo/Resources/Utils/Constants.swift
  PomoTodo/PomoTodo/Sources/Model/Tab/TabModel.swift
  PomoTodo/PomoTodo/Sources/Model/Timer/TimerColorSet.swift
  PomoTodo/PomoTodo/Sources/Model/Timer/TimerDummyModels.swift
  PomoTodo/PomoTodo/Sources/Model/Timer/TimerPhase.swift
  PomoTodo/PomoTodo/Sources/ViewModels/PomoViewModel.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/CircularProgressBar.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/CircularProgressView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/TimerDisplayView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/TimerRunningInnerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PageControl.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoTimerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoTopView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PageControl.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PomoTimerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PomoTopView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/TimerRunningView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/TimerSetupView.swift
Labels: ✨ feature

#28 [feature] 설정 개발
  PomoTodo/PomoTodo.xcodeproj/xcshareddata/xcschemes/PomoTodo.xcscheme
  PomoTodo/PomoTodo/Sources/ViewModels/PomoViewModelSetting.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/PomoDetailSettingView.swift
  PomoTodo/PomoTodo/Sources/Views/SettingView.swift
Labels: ✨ feature

#34 [feature] TimerUseCase 분리
  PomoTodo/PomoTodo/Sources/Domain/UseCase/PomoTodoUseCase.swift
  PomoTodo/PomoTodo/Sources/Domain/UseCase/PomoTodoUseCaseImpl.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
Labels: ✨ feature

#35 [feature] 설정 데이터 연결
  PomoTodo/PomoTodo.xcodeproj/project.pbxproj
  PomoTodo/PomoTodo/Sources/Extensions/TimeInterval+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/PomoDetailSettingView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/SettingView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/SettingViewModel.swift
Labels: ✨ feature

#37 [Feature] pomoVM - Usercase 함수 연결
  PomoTodo/.editorconfig
  PomoTodo/PomoTodo/Sources/Data/Impl/PomoDayRepositoryImpl.swift
  PomoTodo/PomoTodo/Sources/Domain/UseCase/PomoTodoUseCase.swift
  PomoTodo/PomoTodo/Sources/Domain/UseCase/PomoTodoUseCaseImpl.swift
  PomoTodo/PomoTodo/Sources/Extensions/Int+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/TimeInterval+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/UIApplication+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/UIScreen+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/CircularProgressBar.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/CircularProgressView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/TimerDisplayView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ActiveSubviews/TimerRunningInnerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoViewModel.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PageControl.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PomoTimerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/SetupSubviews/PomoTopView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/CircularProgressBar.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/CircularProgressView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/TimerDisplayView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/TimerRunningInnerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/Composite/TimerRunningView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/Composite/TimerSetupView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PageControl.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoTimerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoTopView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/TimerRunningView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/TimerSetupView.swift
Labels: ✨ feature

#46 [Bugfix] 설정, 투두 테스트 이슈 수정
  PomoTodo/PomoTodo/Sources/Domain/UseCase/PomoTodoUseCaseImpl.swift
  PomoTodo/PomoTodo/Sources/Extensions/UIApplication+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/UIScreen+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/PomoDetailSettingView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/SettingView.swift
  PomoTodo/PomoTodo/Sources/Views/ToDo/ToDoView.swift
Labels: 🐞 bug

#45 [feature] 화면 세로 모드, 라이트 모드 고정 및 스플래시 화면, 아이콘 추가
  PomoTodo/PomoTodo.xcodeproj/project.pbxproj
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  PomoTodo/PomoTodo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/launchLogo.imageset/Contents.json
  PomoTodo/PomoTodo/Resources/Assets.xcassets/launchLogo.imageset/launchLogo.png
  PomoTodo/PomoTodo/Resources/Launch Screen.storyboard
Labels: ✨ feature

#47 [Bugfix] 타이머 버그 수정
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoViewModel.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/CircularProgressView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/TimerDisplayView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/TimerRunningInnerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoTopView.swift
Labels: 🐞 bug

#39 [refactor] ToDoViewModel 및 DIContainer 리팩토링
  PomoTodo/PomoTodo.xcodeproj/project.pbxproj
  PomoTodo/PomoTodo/Sources/App/DIContainer.swift
  PomoTodo/PomoTodo/Sources/App/PomoTodoApp.swift
  PomoTodo/PomoTodo/Sources/App/RepositoryProvider.swift
  PomoTodo/PomoTodo/Sources/Data/Impl/PomoDayRepositoryImpl.swift
  PomoTodo/PomoTodo/Sources/Domain/UseCase/PomoTodoUseCaseImpl.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/ToDo/ToDoView.swift
  PomoTodo/PomoTodo/Sources/Views/ToDo/ToDoViewModel.swift
Labels: ✨ feature

#55 [Chore] 깃허브 리드미 정리
  README.md
Labels: 📃 docs

#56 [refactor] 세팅 viewModel 리팩토링
  PomoTodo/PomoTodo.xcodeproj/project.pbxproj
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/PomoDetailSettingView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/SettingView.swift
  PomoTodo/PomoTodo/Sources/Views/Setting/SettingViewModel.swift
Labels: 🔨 refactor

#49 [refactor] 통계VM 리팩토링
  PomoTodo/PomoTodo/Sources/Views/Chart/StatisticsView.swift
  PomoTodo/PomoTodo/Sources/Views/Chart/StatisticsViewModel.swift
Labels: 🔨 refactor

#53 [Refactor] pomoVM 리팩토링 및 타이머 파트 주석 추가
  PomoTodo/PomoTodo/Resources/Utils/Constants.swift
  PomoTodo/PomoTodo/Sources/Extensions/Font+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/Int+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/TimeInterval+Extensions.swift
  PomoTodo/PomoTodo/Sources/Extensions/UIScreen+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/MainTabBarView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/PomoView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/CircularProgressBar.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/CircularProgressView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/TimerDisplayView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/ActiveSubviews/TimerRunningInnerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/Composite/TimerRunningView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/Composite/TimerSetupView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PageControl.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoBottomView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoTimerView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/Subviews/SetupSubviews/PomoTopView.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ViewModel/PomoViewModel+Extensions.swift
  PomoTodo/PomoTodo/Sources/Views/Pomo/ViewModel/PomoViewModel.swift
Labels: 📃 docs, 🔨 refactor
